---
- name: VM Initial Setup
  hosts: all
  become: yes 
  
  pre_tasks:
  - name: Install updates
    apt:
      update_cache: yes
      upgrade: dist

  vars_files:
    - vault
    
  tasks:

     - name: Install packages
       package:
         name:
           - micro
           - curl
           - git
           - neovim
           - gh
           - fail2ban
           - cmatrix
           - htop
           - unzip
           - nmon
           - sysstat
           - snmp
           - snmpd
           - snmp-mibs-downloader
         state: present

     - name: Add MIBs
       shell: sudo sed -i 's/mibs :/# mibs :/g' /etc/snmp/snmp.conf

     - name: Configure aliases 
       get_url:
         url: https://raw.githubusercontent.com/elianmanzueta/linuxstuff/main/files/.bash_aliases
         dest: /home/elian/.bashrc
         owner: root
         group: root
         mode: 0644
     
     - name: Make neovim the default editor
       shell: |
         export EDITOR=nvim >> ~/.bashrc
         source ~/.bashrc

     - name: Configure snmpd.conf
       get_url:
         url: https://raw.githubusercontent.com/elianmanzueta/linuxstuff/main/files/snmpd-configuration
         dest: /etc/snmpd.conf
         owner: root
         group: root
         mode: 0600
     
     - name: Configure the nvim directory
       shell: mkdir ~/.config/nvim 
     
     - name: Configure init.vim
       get_url:
         url: https://raw.githubusercontent.com/elianmanzueta/linuxstuff/main/files/init.vim
         dest: ~/.config/nvim/
         owner: root
         group: root
         mode: 0644

     - name: Disable SSH Forwarding
       shell: echo "DisableForwarding yes" >> /etc/ssh/sshd_config.d/10-my-sshd-settings.conf

     - name: Start/enable fail2ban service
       service:
         name: fail2ban
         state: started

     - name: Enable firewall and permit SSH access
       shell: |
         ufw allow ssh
         ufw --force enable
              
     - name: Cleanup 
       shell: |
         sudo apt clean
         sudo apt autoremove
