---

- hosts: all
  become: true
  pre-tasks: 

  - name: Update repository index
    apt:
      update_cache: yes
      upgrade: yes
    changed_when: false

- hosts: all
  become: true
  roles:
    - base-machine

- hosts: ansible
  become: true
  roles:
    - ansible
