---
- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - python3-pip
      - snmp
      - snmpd
      - snmp-mibs-downloader
      - gh
      - fail2ban
      - cmatrix
      - htop
      - unzip
      - nmon
      - sysstat
      - libfuse2
      - ninja-build
      - build-essential
      - git
      - gettext
      - cmake
      - procps
<<<<<<< HEAD
      - file
      - zsh
=======
>>>>>>> d21b2b9508660b985a50a1b14c9acdda23182248

- name: (pip) Install pynvim
  pip:
    name: pynvim

<<<<<<< HEAD
- name: Clone configuration repository
  git: 
    repo: https://github.com/elianmanzueta/config 
    dest: /home/elian/config  

- name: Run configuration install script
  shell: sh ~/config/scripts/install.sh 
=======
- name: Install nvim
  shell: |
    git clone https://github.com/neovim/neovim
    cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
    make install 
>>>>>>> d21b2b9508660b985a50a1b14c9acdda23182248

- name: Configure neovim
  git:
    repo: https://github.com/elianmanzueta/nvim.git
    dest: /home/elian/.config/nvim
 
- name: Configure snmpd.conf 
  template:
    src: templates/snmpd_config.j2
    dest: /etc/snmp/snmpd.conf

<<<<<<< HEAD
=======
- name: Configure ~/.bashrc
  copy:
    src: files/.bashrc
    dest: /home/elian/.bashrc
    owner: root
    group: root
    mode: '0644'

>>>>>>> d21b2b9508660b985a50a1b14c9acdda23182248
- name: Configure git
  shell: |
    git config --global user.email "eliandmanzueta@gmail.com"
    git config --global user.name "Elian"

- name: Start/enable fail2ban service 
  service:
    name: fail2ban
    state: started

- name: Enable firewall and permit SSH access
  shell: |
    ufw allow ssh
    ufw --force enable
