---
- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - python3-pip
      - snmp
      - snmpd
      - snmp-mibs-downloader
      - gh
      - fail2ban
      - cmatrix
      - htop
      - unzip
      - nmon
      - sysstat
      - libfuse2
      - ninja-build
      - build-essential
      - git
      - gettext
      - cmake

- name: (pip) Install pynvim
  pip:
    name: pynvim

- name: Add MIBs
  command: sed -i 's/mibs :/# mibs :/g' /etc/snmp/snmp.conf

- name: Install nvim
  shell: |
    git clone https://github.com/neovim/neovim
    cd neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo
    make install 

- name: Configure nvim directory
  copy:
    path: /home/elian/.config/nvim
    state: directory
    mode: '0644'

- name: Configure nvim
  git:
    repo: https://github.com/elianmanzueta/nvim.git
    dest: ~/.config/nvim
 
- name: Configure snmpd.conf 
  copy:
    src: files/snmpd.conf 
    dest: /etc/snmp/snmpd.conf
    owner: root
    group: root
    mode: '0644'

- name: Configure ~/.bashrc
  copy:
    src: files/.bashrc
    dest: /home/elian/.bashrc
    owner: root
    group: root
    mode: '0644'

- name: Configure starship
  copy:
    sec: files/starship.toml
    dest: /home/elian/.config/starship.toml 
    owner: root
    group: root
    mode: '0644'

- name: Configure git
  shell: |
    git config --global user.email "eliandmanzueta@gmail.com"
    git config --global user.name "Elian"

- name: Start/enable fail2ban service 
  service:
    name: fail2ban
    state: started

- name: Enable firewall and permit SSH access
  shell: |
    ufw allow ssh
    ufw --force enable
