---
- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - python3-pip
      - snmp
      - snmpd
      - snmp-mibs-downloader
      - gh
      - fail2ban
      - cmatrix
      - htop
      - unzip
      - nmon
      - sysstat
      - libfuse2
      - ninja-build
      - build-essential
      - git
      - gettext
      - cmake
      - procps
      - file
      - zsh

- name: (pip) Install pynvim
  pip:
    name: pynvim

- name: Clone configuration repository
  git: 
    repo: https://github.com/elianmanzueta/config 
    dest: /home/elian/config  

- name: Run configuration install script
  shell: sh ~/config/scripts/install.sh 

- name: Start/enable fail2ban service 
  service:
    name: fail2ban
    state: started

- name: Enable firewall and permit SSH access
  shell: |
    ufw allow ssh
    ufw --force enable
