---
- name: Install sshpass
  apt:
    name: sshpass

- name: Install ansible
  apt:
    name: ansible

- name: Install ansible.community.general collection
  command: ansible-galaxy collection install community.general

- name: Clone ansible repository
  git:
   repo: https://github.com/elianmanzueta/homelab-ansible
   dest: /home/elian/ansible/

- name: Configure repository alias
  shell: |
    echo >> /home/elian/.bashrc
    echo "alias repo='cd /home/elian/ansible" >> /home/elian/.bashrc
