---
- name: Install sshpass
  apt:
    name: sshpass

- name: Install ansible
  apt:
    name: ansible

- name: Install ansible.community.general collection
  command: ansible-galaxy collection install community.general

- name: Check for ansible repository
  stat:
    path: /home/elian/ansible/ 
  register: ansible_dir_info

- name: Clone ansible repository
  git:
    repo: https://github.com/elianmanzueta/homelab-ansible
    dest: /home/elian/ansible/
  when: not ansible_dir_info.stat.exists

