---
- name: Install sshpass
  apt:
    name: sshpass

- name: Install ansible
  apt:
    name: ansible

- name: Clone ansible repository
  git:
   repo: https://github.com/elianmanzueta/homelab-ansible
   dest: /home/elian/ansible/
