all:
  hosts:
    test_vm:
      ansible_host: 192.168.50.121
      ansible_ssh_private_key_file: ~/.ssh/test_vm

    docker:
      ansible_host: 192.168.50.130
      ansible_ssh_private_key_file: ~/.ssh/docker

  vars: 
    ansible_user: elian
